// UYGA YORDAM production server
// deploy sync marker 2026-09-17
const http=require('http'), fs=require('fs'), path=require('path'), crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');
const ROOT=__dirname;
const PORT=Number(process.env.PORT||3000);
const db=new DatabaseSync(path.join(ROOT,'uyga.db'));
db.exec(`CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,service TEXT,price INTEGER,name TEXT,phone TEXT,address TEXT,date TEXT,time TEXT,note TEXT,lat REAL,lon REAL,status TEXT,created TEXT,worker_lat REAL,worker_lon REAL,worker_time TEXT);`);
for(const sql of ['ALTER TABLE orders ADD COLUMN worker_lat REAL','ALTER TABLE orders ADD COLUMN worker_lon REAL','ALTER TABLE orders ADD COLUMN worker_time TEXT']){try{db.exec(sql)}catch(e){if(!String(e.message||e).includes('duplicate column name'))throw e}}
const ADMIN_USER=process.env.ADMIN_USER||'admin',ADMIN_PASS=process.env.ADMIN_PASS||'admin123',WORKER_USER=process.env.WORKER_USER||'worker',WORKER_PASS=process.env.WORKER_PASS||'worker123',SECRET=process.env.AUTH_SECRET||'uyga-yordam-change-me';
function json(res,code,obj){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((ok,fail)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6){req.destroy();fail(new Error('Request too large'))}});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){fail(e)}});req.on('error',fail)})}
function token(r){const e=Date.now()+12*3600e3,p=`${r}.${e}`,s=crypto.createHmac('sha256',SECRET).update(p).digest('hex');return `${p}.${s}`}
function role(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const [r,e,s]=t.split('.');if(!r||!e||!s||!/^[0-9]+$/.test(e)||+e<Date.now())return null;const x=crypto.createHmac('sha256',SECRET).update(`${r}.${e}`).digest('hex'),a=Buffer.from(s),b=Buffer.from(x);return a.length===b.length&&crypto.timingSafeEqual(a,b)?r:null}
function rows(){return db.prepare('SELECT * FROM orders ORDER BY created DESC').all().map(o=>({...o,gps:o.lat==null?null:{lat:o.lat,lon:o.lon},workerGps:o.worker_lat==null?null:{lat:o.worker_lat,lon:o.worker_lon}}))}
function originalHome(html){const home=`<section id="home" class="promo-home"><div class="promo-art"><img src="hero.png" alt="UYGA YORDAM — хизматлар платформаси"><button class="promo-hotspot promo-main-order" type="button" aria-label="Буюртма бериш" onclick="openOrder()"></button><button class="promo-hotspot promo-phone-order" type="button" aria-label="Буюртма бериш" onclick="openOrder()"></button><button class="promo-hotspot promo-bottom-order" type="button" aria-label="Буюртма бериш" onclick="openOrder()"></button>${Array.from({length:12},(_,i)=>`<button class="promo-hotspot promo-service s${i}" type="button" aria-label="Хизмат ${i+1}" onclick="chooseService(${i})"></button>`).join('')}</div><div id="services" class="hidden"></div></section><nav class="home-control" aria-label="Платформа менюси"><button type="button" onclick="show('track')"><span>🔎</span><b>Буюртмани текшириш</b></button><button type="button" onclick="show('worker')"><span>👷</span><b>Ходим</b></button><button type="button" onclick="show('admin')"><span>📊</span><b>Админ</b></button></nav>`;
const css=`<style id="original-uyga-design">body:has(#home.promo-home:not(.hidden)) .top,body:has(#home.promo-home:not(.hidden)) .footer{display:none!important}.wrap:has(#home.promo-home:not(.hidden)){max-width:none!important;padding:0!important}.promo-home{margin:0;width:100%;background:#fff}.promo-art{position:relative;width:100%;line-height:0;overflow:hidden}.promo-art>img{display:block;width:100%;height:auto;margin:0;border-radius:0;box-shadow:none;user-select:none}.promo-hotspot{position:absolute;display:block;padding:0;margin:0;border:0;background:transparent;cursor:pointer;z-index:2}.promo-main-order{left:2.2%;top:30.5%;width:18%;height:4.2%}.promo-phone-order{left:75.5%;top:15.5%;width:11%;height:3.5%}.promo-bottom-order{left:68.2%;top:87.5%;width:18.2%;height:4.5%}.promo-service{width:10.9%;height:10.9%;top:45.8%}.promo-service.s0{left:2.2%}.promo-service.s1{left:14.1%}.promo-service.s2{left:26%}.promo-service.s3{left:37.9%}.promo-service.s4{left:49.8%}.promo-service.s5{left:61.8%}.promo-service.s6{left:2.2%;top:58.2%}.promo-service.s7{left:14.1%;top:58.2%}.promo-service.s8{left:26%;top:58.2%}.promo-service.s9{left:37.9%;top:58.2%}.promo-service.s10{left:49.8%;top:58.2%}.promo-service.s11{left:61.8%;top:58.2%}.home-control{position:fixed;left:50%;transform:translateX(-50%);bottom:18px;z-index:100000;display:flex;gap:8px;align-items:center;width:max-content;max-width:calc(100vw - 24px);padding:8px;border:1px solid rgba(255,255,255,.95);border-radius:18px;background:rgba(255,255,255,.97);box-shadow:0 12px 40px rgba(0,0,0,.25);backdrop-filter:blur(12px)}.home-control button{appearance:none;padding:11px 15px;border:0;border-radius:12px;background:#eef8f6;color:#087f79;font-weight:800;white-space:nowrap;box-shadow:inset 0 0 0 1px #dcebe8;cursor:pointer}.home-control span{margin-right:5px}@media(max-width:700px){.home-control{left:7px;right:7px;transform:none;bottom:8px;width:auto;max-width:none;justify-content:stretch;gap:5px;padding:5px;border-radius:15px}.home-control button{flex:1;padding:10px 5px;font-size:12px}.home-control button:first-child{flex:1.45}}</style>`;
const start=html.indexOf('<section id="home"');if(start<0)return html;const end=html.indexOf('</section>',start);if(end<0)return html;const replaced=html.slice(0,start)+home+html.slice(end+10);return replaced.includes('class="promo-home"')?replaced.replace('</head>',css+'<script src="/pricing.js" defer></script></head>'):html}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');
if(req.method==='POST'&&u.pathname==='/api/login'){const b=await body(req),r=(b.username===ADMIN_USER&&b.password===ADMIN_PASS)?'admin':(b.username===WORKER_USER&&b.password===WORKER_PASS)?'worker':null;return r?json(res,200,{token:token(r),role:r}):json(res,401,{error:'Нотўғри логин ёки парол'})}
if(req.method==='POST'&&u.pathname==='/api/orders'){const b=await body(req);if(!b.id||!b.name||!b.phone||!b.address)return json(res,400,{error:'Маълумот етарли эмас'});if(!/^UY-[A-Z0-9-]{6,20}$/.test(String(b.id)))return json(res,400,{error:'Нотўғри буюртма рақами'});if(db.prepare('SELECT id FROM orders WHERE id=?').get(b.id))return json(res,409,{error:'Бу буюртма рақами аллақачон мавжуд'});db.prepare(`INSERT INTO orders(id,service,price,name,phone,address,date,time,note,lat,lon,status,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.id,b.service||'',Number(b.price)||0,b.name,b.phone,b.address,b.date||'',b.time||'',b.note||'',Number.isFinite(Number(b.lat))?Number(b.lat):null,Number.isFinite(Number(b.lon))?Number(b.lon):null,'Янги',new Date().toISOString());return json(res,201,{ok:true,id:b.id})}
if(req.method==='GET'&&u.pathname.startsWith('/api/orders/')){const id=decodeURIComponent(u.pathname.split('/').pop()),o=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o)return json(res,404,{error:'Топилмади'});return json(res,200,{...o,gps:o.lat==null?null:{lat:o.lat,lon:o.lon},workerGps:o.worker_lat==null?null:{lat:o.worker_lat,lon:o.worker_lon}})}
if(req.method==='GET'&&u.pathname==='/api/orders'){const r=role(req);if(r!=='admin'&&r!=='worker')return json(res,401,{error:'Кириш керак'});return json(res,200,rows())}
if(req.method==='PATCH'&&u.pathname.startsWith('/api/orders/')){const r=role(req);if(r!=='admin'&&r!=='worker')return json(res,403,{error:'Рухсат йўқ'});const id=decodeURIComponent(u.pathname.split('/').pop()),b=await body(req),allowed=['Янги','Ходим бириктирилди','Йўлда','Бажарилмоқда','Тугади'];if(!allowed.includes(b.status))return json(res,400,{error:'Нотўғри ҳолат'});if(!db.prepare('SELECT id FROM orders WHERE id=?').get(id))return json(res,404,{error:'Буюртма топилмади'});const lat=Number(b.lat),lon=Number(b.lon),hasGps=Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lon)&&lon>=-180&&lon<=180;if(r==='worker'&&hasGps)db.prepare('UPDATE orders SET status=?,worker_lat=?,worker_lon=?,worker_time=? WHERE id=?').run(b.status,lat,lon,new Date().toISOString(),id);else db.prepare('UPDATE orders SET status=? WHERE id=?').run(b.status,id);return json(res,200,{ok:true,workerGps:hasGps?{lat,lon}:null,workerTime:hasGps?new Date().toISOString():null})}
if(req.method==='DELETE'&&u.pathname==='/api/orders'){if(role(req)!=='admin')return json(res,403,{error:'Рухсат йўқ'});db.exec('DELETE FROM orders');return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true});const p=u.pathname==='/'?'index.html':u.pathname.slice(1),f=path.join(ROOT,p);if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('404')}const ext=path.extname(f),ct={'.html':'text/html; charset=utf-8','.png':'image/png','.json':'application/json','.js':'text/javascript'}[ext]||'application/octet-stream';if(p==='index.html'){const html=originalHome(fs.readFileSync(f,'utf8'));res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-store, no-cache, must-revalidate, proxy-revalidate','Pragma':'no-cache','Expires':'0'});return res.end(html)}res.writeHead(200,{'Content-Type':ct,'Cache-Control':'public, max-age=3600'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'Server error'});else res.end()}});server.listen(PORT,()=>console.log(`UYGA YORDAM http://localhost:${PORT}`));
